stages:
- test       # Deploy to a DEV system for testing
- staging    # Deploy to IRC/NLE (manually)
- production # Deploy to LIVE (manually)
- check      # Run checks across all environments

variables:
  # Our servers old git version does not support fetching, see https://stackoverflow.com/questions/56663096/gitlab-runner-doesnt-work-on-a-specific-project
  GIT_STRATEGY: clone
  # Shared Docker-group-writable storage paths for different environments:
  DEV_STORAGE_PATH: /mnt/nfs/data/npld-access-stack
  DLS_STORAGE_PATH: /home/axsadmin/service-storage

# -------------------------------------------------------------------------------------
# Job templates re-used across stages, so each job only specifies what's different
# -------------------------------------------------------------------------------------

.configure:
  variables:
    STORAGE_PATH_SHARED: ${DLS_STORAGE_PATH}
  script:
    - mkdir -p ${STORAGE_PATH_SHARED}/prometheus-data
    - ./clone-or-pull-acls.sh
  only:
    - main

.deploy:
  variables:
    LOCKS_AUTH: $LOCKS_AUTH_DEV
    STORAGE_PATH_SHARED: ${DLS_STORAGE_PATH}
    STORAGE_PATH_ACL: ${STORAGE_PATH_SHARED}/wayback_excludes_update/ldukwa/acl
    STORAGE_PATH_PROMETHEUS: ${STORAGE_PATH_SHARED}/prometheus-data
    PYWB_IMAGE: ukwa/ukwa-pywb:custom-viewers
    EXTRA_CONFIG: 
  before_script:
    # These credentials are only valid during the time the job runs, so deployment must wait for images to be fetched.
    - echo $CI_DEPENDENCY_PROXY_PASSWORD | docker login --username $CI_DEPENDENCY_PROXY_USER --password-stdin $CI_DEPENDENCY_PROXY_SERVER
  script:
    - ./deploy-rrwb.sh
  only:
    - main

# -------------------------------------------------------------------------------------
# Test Stage deployment in DEV environment
# -------------------------------------------------------------------------------------

configure_dev:
  extends: .configure
  stage: test
  variables:
    STORAGE_PATH_SHARED: ${DEV_STORAGE_PATH}
  tags:
    - dev  

deploy_dev:
  extends: .deploy
  stage: test
  environment:
    name: dev
    url: http://dev1.n45.wa.bl.uk:8209/
  variables:
    STORAGE_PATH_SHARED: ${DEV_STORAGE_PATH}
    DLS_ACCESS_SERVER: http://staffaccess.dl.bl.uk
    EXTRA_CONFIG: -c docker-compose.dev.yml
  tags:
    - dev

# -------------------------------------------------------------------------------------
# Staging deployment in IRC environment
# -------------------------------------------------------------------------------------

configure_irc:
  extends: .configure
  stage: staging
  # Only run manually
  when: manual
  tags:
    - irc-bsp-npld.dom.test

deploy_irc:
  extends: .deploy
  stage: staging
  # Only run manually
  when: manual
  environment:
    name: irc-bsp
    url: https://blstaff-alpha.ldls.org.uk/
  variables:
    DLS_ACCESS_SERVER: http://192.168.217.72
  tags: 
    - irc-bsp-npld.dom.test


# -------------------------------------------------------------------------------------
# Production deployment in LIVE environment
# -------------------------------------------------------------------------------------

configure_live_bsp:
  extends: .configure
  stage: production
  when: manual # Only run manually
  tags:
    - dls-bsp-npld.dom.live

deploy_live_bsp:
  extends: .deploy
  stage: production
  environment:
    name: live-bsp
    url: https://blstaff-beta.ldls.org.uk/
  variables:
    DLS_ACCESS_SERVER: http://192.168.218.72
  tags: 
    - dls-bsp-npld.dom.live

configure_live_lon:
  extends: .configure
  stage: production
  when: manual # Only run manually
  tags:
    - dls-lon-npld.dom.live

deploy_live_lon:
  extends: .deploy
  stage: production
  environment:
    name: live-lon
    url: https://blstaff-beta.ldls.org.uk/
  variables:
    DLS_ACCESS_SERVER: http://192.168.218.72
  tags: 
    - dls-lon-npld.dom.live

# -------------------------------------------------------------------------------------
# Checks and metrics
# -------------------------------------------------------------------------------------

# This job gets the NGINX metrics as a local file and stores it as an artefact:
Get Metrics 1/2:
  stage: check
  when: manual
  script:
    - curl -o nginx.metrics.dev http://127.0.0.1:3903/metrics
  artifacts:
    paths:
      - nginx.metrics.dev
    expire_in: 1 day
  tags:
    - dev
    #- irc-bsp-npld.dom.test

Get Metrics 2/2:
  stage: check
  needs:
    - job: Get Metrics 1/2
      artifacts: true
  script:
    - head nginx.metrics.dev
  tags:
    - beta
