build:
  stage: build
  script: echo "Define your build script!"
  environment: dev
  tags:
  - dev

deploy-dev:
  stage: deploy
  environment: dev
  variables:
    LOCKS_AUTH: $LOCKS_AUTH_DEV
    STORAGE_PATH_SHARED: /mnt/nfs/data/airflow/data_exports
    PYWB_IMAGE: ukwa/ukwa-pywb:custom-viewers
    PUSHPROX_URL: http://dev1.n45.wa.bl.uk:9494/
    PUSHPROX_FQDN: dev1.n45.wa.bl.uk
    EXTRA_CONFIG: -c docker-compose.dev.yml
    DLS_ACCESS_SERVER: http://staffaccess.dl.bl.uk
  script:
    - echo "LOCKS_AUTH = $LOCKS_AUTH"
    - echo "STORAGE_PATH_SHARED = $STORAGE_PATH_SHARED"
    - echo "PYWB_IMAGE = $PYWB_IMAGE"
    - echo "PUSHPROX_URL = $PUSHPROX_URL"
    - echo "PUSHPROX_FQDN = $PUSHPROX_FQDN"
    - echo "EXTRA_CONFIG = $EXTRA_CONFIG"
    - echo "DLS_ACCESS_SERVER = $DLS_ACCESS_SERVER"
    - export
    - docker stack deploy -c docker-compose.yml $EXTRA_CONFIG access_rrwb
  only:
    - master
  tags:
    - dev
    - review-apps
    - deploy


deploy_review:
  stage: deploy
  script:
    - echo "Add script here that deploys the code to your infrastructure"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

