
# This is the base configuration. 
version: '3.2'

services:

  # -------------------------------------------------------------
  # Staff Access Service Configuration (no locks):
  # -------------------------------------------------------------
  pywb-staff:
    image: ${PYWB_IMAGE}
    environment:
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
    volumes:
      - ./pywb/staff.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/logo-staff.png:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8309:8080"


  # -------------------------------------------------------------
  # Reading Room Wayback with SCU locks, per LDL:
  # -------------------------------------------------------------
  pywb-bl:
    image: ${PYWB_IMAGE}
    environment:
      - "REDIS_URL=redis://redis:6379/0" # Locks stored in Redis DB 0
      - "LOCKS_AUTH=${LOCKS_AUTH}"
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
      - "LOCK_PING_INTERVAL=5"
      - "LOCK_PING_EXTEND_TIME=10"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/bl_logo.png:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8300:8080"

  pywb-nls:
    image: ${PYWB_IMAGE}
    environment:
      - "REDIS_URL=redis://redis:6379/1"
      - "LOCKS_AUTH=${LOCKS_AUTH}"
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
      - "LOCK_PING_INTERVAL=5"
      - "LOCK_PING_EXTEND_TIME=10"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/nls_logo.png:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8301:8080"

  pywb-llgc:
    image: ${PYWB_IMAGE}
    environment:
      - "REDIS_URL=redis://redis:6379/2"
      - "LOCKS_AUTH=${LOCKS_AUTH}"
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
      - "LOCK_PING_INTERVAL=5"
      - "LOCK_PING_EXTEND_TIME=10"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/llgc_logo.png:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8302:8080"

  pywb-cam:
    image: ${PYWB_IMAGE}
    environment:
      - "REDIS_URL=redis://redis:6379/3"
      - "LOCKS_AUTH=${LOCKS_AUTH}"
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
      - "LOCK_PING_INTERVAL=5"
      - "LOCK_PING_EXTEND_TIME=10"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/cambridge_logo.jpg:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8303:8080"

  pywb-bod:
    image: ${PYWB_IMAGE}
    environment:
      - "REDIS_URL=redis://redis:6379/4"
      - "LOCKS_AUTH=${LOCKS_AUTH}"
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
      - "LOCK_PING_INTERVAL=5"
      - "LOCK_PING_EXTEND_TIME=10"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/bodleian_logo.jpg:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8304:8080"

  pywb-tcd:
    image: ${PYWB_IMAGE}
    environment:
      - "REDIS_URL=redis://redis:6379/5"
      - "LOCKS_AUTH=${LOCKS_AUTH}"
      - "TLDEXTRACT_CACHE_TIMEOUT=0.1"
      - "LOCK_PING_INTERVAL=5"
      - "LOCK_PING_EXTEND_TIME=10"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
      - ./logos/trinity_logo.jpg:/ukwa_pywb/static/ukwa-2018-w-med.png
    depends_on:
      - redis
      - doc-streamer
    ports:
      - "8305:8080"



  # -------------------------------------------------------------
  # Supporting Services:
  # -------------------------------------------------------------

  # Redis service to hold locks
  redis:
    image: redis:6

  # PushProx to enable integration with Prometheus monitoring
  pushprox-client:
    image: prom/pushprox:v0.1.0
    entrypoint: '/app/pushprox-client'
    command:
      - '--fqdn=${PUSHPROX_FQDN}' # Should point to the host server so any ports can be accessed.
      - '--proxy-url=${PUSHPROX_URL}'

  # Add some setup via NGINX
  nginx:
    image: nginx:1
    command: /opt/mtail/entrypoint.sh
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/mtail:/opt/mtail:ro
      #- ./nginx/logs:/var/log/nginx:rw
    ports:
      - "8100:8100" # Shared port (service determine by Host header)
      - "8200:8200" # BL
      - "8201:8201" # NLS
      - "8202:8202" # LLGC
      - "8203:8203" # CUL
      - "8204:8204" # BOD
      - "8205:8205" # TCD
      - "8209:8209" # Staff (default when Host header does not match)
      - "3903:3903" # mtail port for monitoring
    depends_on:
      - pywb-staff
      - pywb-bl
      - pywb-nls
      - pywb-llgc
      - pywb-cam
      - pywb-bod
      - pywb-tcd
    networks:
      default:
        aliases: # So Docker services on the internal network can resolve services by name:
          - bl.ldls.org.uk
          - nls.ldls.org.uk
          - llgc.ldls.org.uk
          - cam.ldls.org.uk
          - bodleian.ldls.org.uk
          - tcdlibrary.ldls.org.uk

  # ePub Streamer/Unzipper
  doc-streamer:
    image: ukwa/epub-streamer:main
    environment:
      - ARK_SERVER=http://staffaccess.dl.bl.uk

#logging:
#  driver: gelf
#  options:
#    gelf-address: "udp://logs.wa.bl.uk:12201"

