
# This is the base configuration. 
version: '3.2'

services:

  # -------------------------------------------------------------
  # Staff Access Service Configuration (no locks):
  # -------------------------------------------------------------
  pywb-staff:
    image: ukwa/ukwa-pywb:2.6.3
    environment:
      - "UKWA_INDEX=xmlquery+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://hdfs.api.wa.bl.uk"
    volumes:
      - ./pywb/staff.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
    depends_on:
      - redis
    ports:
      - "8309:8080"


  # -------------------------------------------------------------
  # Reading Room Wayback configuration per LDL:
  # -------------------------------------------------------------
  pywb-bl:
    image: ukwa/ukwa-pywb:2.6.3
    environment:
      - "UKWA_INDEX=xmlquery+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://hdfs.api.wa.bl.uk"
      - "REDIS_URL=redis://redis:6379/0"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
    depends_on:
      - redis
    ports:
      - "8300:8080"

  pywb-nls:
    image: ukwa/ukwa-pywb:2.6.3
    environment:
      - "UKWA_INDEX=xmlquery+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://hdfs.api.wa.bl.uk"
      - "REDIS_URL=redis://redis:6379/1"
    volumes:
      - ./pywb/readingroom.yaml:/webarchive/config.yaml
      - ${STORAGE_PATH_SHARED}:/ukwa_pywb/acl/
    depends_on:
      - redis
    ports:
      - "8301:8080"

  # Redis service to hold locks
  redis:
    image: redis:6

  # Add some setup via NGINX
  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
    ports:
      - "8100:8100"
      - "8200:8200"
      - "8201:8201"
      - "8209:8209"
    depends_on:
      - pywb-staff
      - pywb-bl
      - pywb-nls
    networks:
      default:
        aliases:
          - bl.ldls.org.uk
          - nls.ldls.org.uk

#logging:
#  driver: gelf
#  options:
#    gelf-address: "udp://logs.wa.bl.uk:12201"

