
# This is the base configuration. 
version: '3.2'

services:

  # Redis Browser      
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=redis_bl:redis:6379:0,redis_nls:redis:6379:1,redis_llgc:redis:6379:2,redis_cam:redis:6379:3,redis_bod:redis:6379:4,redis_tcd:redis:6379:5
    ports:
    - "8081:8081"
    depends_on:
    - redis

