global:
  external_labels:
    system: 'rrwb'
    system_name: 'reading-room-wayback'
  relabel_configs:
    - source_labels: [__meta_dockerswarm_node_hostname]
      target_label: docker_node

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rrwb-nginx'
    static_configs:
      - targets: ['nginx:3903']

