global:
  external_labels:
    system: 'rrwb'
    system_name: 'reading-room-wayback'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rrwb-nginx'
    static_configs:
      - targets: ['nginx:3903']

