global:
  external_labels:
    system: 'rrwb'
    system_name: 'npld-reading-room-access-pywb'
    hostname: '${HOSTNAME}'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rrwb-nginx'
    static_configs:
      - targets: ['nginx:3903']

