INDEX:   &INDEX ${UKWA_INDEX}
ARCHIVE: &ARCHIVE ${UKWA_ARCHIVE}

collections:
    # NPLD access under /archive/
    archive:
        index_paths: *INDEX
        archive_paths: *ARCHIVE

        acl_paths:
            - ./acl/blocks.aclj

        default_access: allow

        # up the query limit:
        query_limit: 100000

        # Enable SCU locks
        single-use-lock: true

    # Access to internal documents using live web support:
    # TODO Test if this actually works!
    access:
        index: $live
        single-use-lock: true

proxy:
    # collection for proxy mode
    coll: archive
    ca_name: UKWA pywb HTTPS Proxy CA
    enable_content_rewrite: false


# redirect to exact url behavior
redirect_to_exact: true

# enable memento
enable_memento: true

# enable experimental Memento Prefer
enable_prefer: true

# Locale setup
locales_root_dir: ./i18n/translations/
locales:
  - en
  - cy

